name: mbarete_padel
description: "App para reserva de cancha"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  calendar_view: ^1.4.0
  dio: ^5.4.1
  easy_loader: ^2.0.0
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_messaging: 14.7.19
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  flutter_riverpod: ^2.5.1
  formz: ^0.7.0
  go_router: ^7.1.1
  google_sign_in: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.18.1
  item_count_number_button: ^1.9.2
  select_field: ^1.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  color_dark: "#1a1717"
  image_dark: "assets/logo_dark.png"
  android_12:
    image: assets/logo_12.png
    image_dark: assets/logo_dark_12.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - .env
