// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7iX1cipnMZdhXTrbLjwXVWR2kWF6yl_M',
    appId: '1:729664463444:android:dd94d876d06263e4c7c3c1',
    messagingSenderId: '729664463444',
    projectId: 'mbarete-padel',
    storageBucket: 'mbarete-padel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEVFnQgoUEpYyMjXPd6rN2ILzOB_6q0Ew',
    appId: '1:729664463444:ios:325a2f4feb98a6edc7c3c1',
    messagingSenderId: '729664463444',
    projectId: 'mbarete-padel',
    storageBucket: 'mbarete-padel.appspot.com',
    androidClientId: '729664463444-re6h403q2o40ctc4fg5hro8e3tcg0f23.apps.googleusercontent.com',
    iosClientId: '729664463444-1r2tdj9ttj30mdk9fq2154d7bhqf4ss4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mbaretePadel',
  );
}
